### ISSUE TITLE
Organising Local Storage

### ISSUE THREAD

**Issue by marianphillips** [boolean-uk/team-dev-client#121]
## Tasks
-Create a single module that deals with local storage
- create functions that the app can use (saveStorage(role, token, userId), loadStorage(), clearStorage())
- make changes to existing code to use these functions and access the data where required. 

## Check List
**Before PR**
- [x] Have tested locally using the local server (with a faked or a real response)
- [x] Have reviewed any new UI with the product owner
- [x] There are no warnings or errors on Chrome Console or Terminal
- [x] The Cypress tests pass
- [x] Any errors from server calls are handled and messaged to the user
- [x] Styling is consistent with the rest of the application
- [x] Use of Material UI components is consistent with the rest of the appliction
- [x] Code formatting sticks to the agreed conventions
- [x] Code has been refactored to extract any relevant components

**After PR Merge**
- [ ] Have verified the new feature works on the deployed build using the live server
