### ISSUE TITLE
#59 Feat: As a user, so I know when something goes wrong, I'd like to see easy to understand error messages 

### ISSUE THREAD

**Issue by rels742** [boolean-uk/team-dev-client#341]
**Issue**
*In the client, most errors are handled by a catch that logs the error to the console.*

- We need to replace all of these with useful error messages for the user
- If the error contains useful information the user might want to know, this should be displayed in an easy to understand way
- No snippets of code, application-level error messages or other technical details should be exposed
- Errors must display in clear sight of the user

**Todos**
- Create or update status messages for the following pages
  - Login
     - [x] User enters an invalid email address or password  
  - Registration
    - [x]  User tries to create a user with an **email** that is already taken in
    - [x]  User enters an invalid **email address** 
    - [x]  User enters invalid website address for **github**
  - Profile / Edit Profile
    - [x] User successfully updates their profile
    - [x] User inputs an invalid URL (profile pic or github link)
   - Account / Update Email
    - [x] User successfully changes their email 
    - [x] User enters an invalid email address
    - [x] User tries to enter the email address already **associated with this account**
    - [x] User tries to enter an email address already **associated with another account**
    - [x] User updates their post privacy
   - Create / Name Cohort
    - [x] User tries to create **without entering a name**
    - [x] User successfully creates a cohort
    - [x] User tries to update a cohort name **without entering a new name**
    - [x] User successfully updates a cohort name
   - Teacher Admin
    - [x] User tries to search for a student **without entering a name**

**Plan**
- Go through all components and examine the `catch` errors.
- Check them against the server-side error responses.
- Take a look at the different HTTP response status codes and come up with error messages easy for end users to understand.  (For example a `404 status code` message for end users could be: "This page could not be found".)
- Use a variety of material UI `Alerts` to display the appropriate messages. 
- `useState` and conditional rendering will be used to trigger the visual alerts to users.

**Comment by shahzadnaeem** [comment]
Looks ok. Will you be looking at all `fetch` calls to see if any `catch` blocks are missing?

**Comment by rels742** [comment]
> Looks ok. Will you be looking at all `fetch` calls to see if any `catch` blocks are missing?

Yes will also check over them to see if any are missing.
