### ISSUE TITLE
#69 As a user, so I can leave the course, I want to deactivate my account

### ISSUE THREAD

**Issue by hubertlemczak** [boolean-uk/team-dev-client#377]
### Tasks

- [ ] Data from server should replace all details with `[removed]` in the response
   - This should allow the client side code to still work correctly 
- [ ] Conditional rendering in PostItem.js and CommentItem.js
   - [ ] Like, username and comment will have event handlers disabled and `cursor: not-allowed` on hover
- [ ] `useState` for `isActive` 
- [ ] if statement in `handleClick` that checks if  'isActive' is set to true or false
- [ ] Conditional rendering like, edit, reply buttons for comments and replies: only render when an account is active. Comments and replies can be deleted by the teachers and admins even when an account is deactivated. 

![image](https://user-images.githubusercontent.com/100080535/192770630-faaae925-33be-4c5b-b9da-69f18e855728.png)

**Comment by rels742** [comment]
L

**Comment by ning905** [comment]
Could also make the username, comment area and like button unclickable so a user can't leave new comments or likes on a removed post.

**Comment by vherus** [comment]
Looks good, I just have one addition for you.

> Teacher area search should not contain removed users

The teachers & admins should still be able to see all user accounts, but there should be something to show that the account is not active. They still must be able to perform on an activate account all of the operations they can on an active account

**Comment by hubertlemczak** [comment]
Will they see the original conent and users in the posts section too or will they see removed?

**Comment by vherus** [comment]
I'll leave that up to you to decide. Take this into consideration:

- As an admin / teacher, should I be able to edit / delete a users posts to remove nasty content even if they've deactivated their account?

**Comment by hubertlemczak** [comment]
The deactivated account's data will be sent over to the client instead of being formatted on the server, is this fine?

**Comment by ning905** [comment]
- Add a deactivate button in the user’s account page.
- Create a state ‘confirmDeactivate’, default as false
- When the user clicks on the deactivate button, a form will pop up, requiring the user to input their login details (email and password). 
<img width="437" alt="Screenshot 2022-10-04 at 16 20 37" src="https://user-images.githubusercontent.com/95832213/193859432-ac106ee4-ef33-4aa7-a168-1f22933fe4db.png">

- If the user submits the form, a POST request will be sent to “[http://localhost:4000/user/:id](http://localhost:4000/user/id)”, with the login details as the body.
- If the server responses with “success”, set confirmDeactivate to true, dialog content will change to requiring the user to confirm deactivating. 
	- If the server responses with error, display error message on the page.
<img width="438" alt="Screenshot 2022-10-04 at 16 21 07" src="https://user-images.githubusercontent.com/95832213/193859558-8f8b00fa-c266-493c-9ebd-7bdfba965a73.png">

- If the user clicks confirm, a PATCH request will be sent to “[http://localhost:4000/user/:id](http://localhost:4000/user/id)”, request body will be ```{ isActive: false}```
- If the user clicks “cancel” or anywhere outsdie of the form during the whole process, the form will be closed, and confirmDeactivate will be set to false

**Comment by Auenc** [comment]
I think that's a good plan for setting a user to be in-active. Good job!
