### ISSUE TITLE
#72 As a user, so I can remove mean comments, I want to be able to delete comments on my posts.

### ISSUE THREAD

**Issue by hubertlemczak** [boolean-uk/team-dev-client#381]
### Tasks

- [ ] Create Edit comment Button
   - [ ] To edit a comment the user must be the comment author [API-Spec](https://hubertlemczak.github.io/team-dev-api/#/comment/editComment)
- [ ] Create Delete comment button
- [ ] To see the delete a comment button one of the following checks must pass [API-Spec](https://hubertlemczak.github.io/team-dev-api/#/comment/deleteComment)
   - [ ] Check if the user is the author of the comment
   - [ ] Check if the user is the author of the post the comment is linked to
   - [ ] Check is user role is `TEACHER` or `ADMIN`
<img width="502" alt="Screenshot 2022-09-28 at 17 09 52" src="https://user-images.githubusercontent.com/97852902/192831552-4365bfa8-0e3d-46a0-8de6-3186bd58b992.png">

**Comment by vherus** [comment]
Great stuff! Approved
